package net.matsudamper.mastodon.rss.frontend

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import kotlinx.coroutines.launch
import net.matsudamper.mastodon.rss.admin.api.AdminPasswordPolicy
import net.matsudamper.mastodon.rss.admin.api.AdminSessionResponse

/**
 * パスワードハッシュを作る画面。
 *
 * 生成はサーバー側で行う。ブラウザで計算すると同じ PBKDF2 の実装をもう一つ
 * 持つことになり、反復回数や形式がずれると「作れるがログインできない」ハッシュが
 * できあがる。作った値をサーバーが覚えることはなく、環境変数に入れて
 * 起動し直すまでは何も変わらない。
 *
 * 打ち間違いに気付けないので確認用の入力を用意している。ハッシュは戻せないため、
 * 間違えたまま環境変数に入れると誰もログインできなくなる。
 */
@Composable
internal fun PasswordHashScreen(
    api: AdminApiClient,
    session: AdminSessionResponse,
    onBack: () -> Unit,
) {
    var password by remember { mutableStateOf("") }
    var confirmation by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<String?>(null) }
    var errorMessage by remember { mutableStateOf<String?>(null) }
    var busy by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()

    // 設定済みのサーバーで作り直せるのはログインした人だけ。未設定のうちは誰でも作れる
    val allowed = !session.loginConfigured || session.authenticated

    AdminPage(title = "パスワードハッシュの作成") {
        if (!allowed) {
            Text("作り直すにはログインが必要。")
            TextButton(onClick = onBack) {
                Text("戻る")
            }
            return@AdminPage
        }

        Text(
            text =
                "ここで作った値を環境変数に入れてサーバーを起動し直すと、" +
                    "そのパスワードでログインできるようになる。",
            style = MaterialTheme.typography.bodyMedium,
        )

        OutlinedTextField(
            value = password,
            onValueChange = {
                password = it
                generated = null
            },
            label = { Text("パスワード（${AdminPasswordPolicy.MIN_LENGTH} 文字以上）") },
            singleLine = true,
            visualTransformation = PasswordVisualTransformation(),
            enabled = !busy,
            modifier = Modifier.fillMaxWidth(),
        )

        OutlinedTextField(
            value = confirmation,
            onValueChange = {
                confirmation = it
                generated = null
            },
            label = { Text("確認のためもう一度") },
            singleLine = true,
            visualTransformation = PasswordVisualTransformation(),
            enabled = !busy,
            modifier = Modifier.fillMaxWidth(),
        )

        val matched = password == confirmation
        val longEnough = password.length >= AdminPasswordPolicy.MIN_LENGTH

        if (confirmation.isNotEmpty() && !matched) {
            Text(text = "2 つの入力が一致していない。", color = MaterialTheme.colorScheme.error)
        }

        val currentError = errorMessage
        if (currentError != null) {
            Text(text = currentError, color = MaterialTheme.colorScheme.error)
        }

        Button(
            enabled = !busy && matched && longEnough,
            onClick = {
                busy = true
                errorMessage = null
                generated = null
                scope.launch {
                    when (val result = api.createPasswordHash(password)) {
                        is AdminResult.Success -> {
                            generated = "${result.value.environmentVariable}=${result.value.hash}"
                        }

                        is AdminResult.Failure -> {
                            errorMessage = result.message
                        }
                    }
                    busy = false
                }
            },
        ) {
            Text("ハッシュを作る")
        }

        val generatedLine = generated
        if (generatedLine != null) {
            // 読み取り専用の入力欄に入れているのは、canvas に描いた文字は
            // ブラウザの選択でコピーできないため。入力欄なら選択してコピーできる
            OutlinedTextField(
                value = generatedLine,
                onValueChange = {},
                readOnly = true,
                label = { Text("環境変数に入れる値") },
                modifier = Modifier.fillMaxWidth(),
            )
            Text(
                text =
                    "この 1 行を環境変数に設定してサーバーを起動し直す。" +
                        "docker compose なら .env に貼る。値はここには保存されていないので、" +
                        "閉じる前にコピーすること。",
                style = MaterialTheme.typography.bodyMedium,
            )
        }

        TextButton(onClick = onBack) {
            Text("戻る")
        }
    }
}
