schema {
    query: Query
    mutation: Mutation
}

type Query {
    admin: AdminQuery!

    "公開アカウントの一覧"
    accounts(cursor: String, limit: Int!): AccountsConnection! @lazy
    account(username: String!): Account @lazy

    "アカウントが配信した投稿。新しい順"
    notes(query: AccountNotesQuery!): AccountNotesConnection! @lazy

    "アカウントが配信した投稿 1 件"
    note(username: String!, id: PublicNoteId!): AccountNote
}

type Mutation {
    admin: AdminMutation!
}

type AccountsConnection {
    nodes: [Account!]!
    pageInfo: PageInfo!
}

type PageInfo {
    hasMore: Boolean!
    nextCursor: String
}
